# Generated by Django 5.2.7 on 2025-10-27 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='designation',
        ),
    ]
