# Generated by Django 5.2.7 on 2025-10-28 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_remove_feedback_designation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='created_at',
            new_name='submitted_at',
        ),
    ]
