# Generated by Django 5.2.7 on 2025-10-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_rename_created_at_feedback_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
