# Generated by Django 5.2.8 on 2025-11-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_feedback_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('contact_person', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
