"""
Django settings for Employee_Feedback_System project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import logging
import os
from logging.handlers import TimedRotatingFileHandler
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8gjp3ybi=)%s==^fk)u-5^5gj49*)4xy5+v6$+!6go*g%=s_f8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost','Sarthak22.pythonanywhere.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts.apps.AccountsConfig',
    'feedback.apps.FeedbackConfig',
    'activity_log.apps.ActivityLogConfig',
    'rest_framework',
    'api',
]

MIDDLEWARE = [
    
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'activity_log.middlewares.LoginActivityMiddleware',
    #'activity_log.middlewares.LogoutActivityMiddleware',
    'Employee_Feedback_System.middleware.exception_logger.ExceptionLoggingMiddleware',
    'Employee_Feedback_System.middleware.force_404.Force404Middleware',
    
]

ROOT_URLCONF = 'Employee_Feedback_System.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Employee_Feedback_System.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'employee_feedback_system',
        'USER': 'root',
        'PASSWORD': 'XFactrr@2293',
        'HOST': 'localhost',
        'PORT' : '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'dashboard_redirect'

LOGOUT_REDIRECT_URL = 'login'

LOGGING={
    'version':1,
    'disable_existing_loggers':False,

    'formatters':{
        'standard':{
            'format':'{levelname} {name}: {message} [{asctime}]',
            'style':'{',
        },
        'simple':{
            'format': '{levelname}: {message}',
            'style':'{',
        },
    },

    'handlers':{
        'file':{
            'level':'DEBUG', #capture all levels (DEBUG & above)
            'class': 'logging.FileHandler',
            'filename': 'logs/project_logs.log',
            'formatter':'standard',
        },
        'console':{
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },

    'loggers':{
        'django':{ #logs built in meassages
            'handlers':['file', 'console'],
            'level': "INFO",
            'propagate':True,
        },

        'accounts':{
            'handlers':['file', 'console'],
            'level': "DEBUG",
            'propagate':False,
        },

        'feedback':{
            'handlers':['file', 'console'],
            'level': "DEBUG",
            'propagate':False,
        },

        'activitylog':{
            'handlers':['file', 'console'],
            'level': "DEBUG",
            'propagate':False,
        },
    }
}

REST_FRAMEWORK={
    'DEFAULT_PERMISSION_CLASSES':['rest_framework.permissions.IsAuthenticated']
}

#SMTP
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'sarthakrupnawar46@gmail.com'
EMAIL_HOST_PASSWORD = 'dded nkse wcej pgec'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

CELERY_BROKER_URL = "redis://192.168.56.101:6379/0"
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Kolkata'
