# Generated by Django 5.2.7 on 2025-11-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_modified_at_userprofile_modified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contact_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
