# Generated by Django 5.2.7 on 2025-11-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_contact_no_userprofile_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contact_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
